### ISSUE TITLE
Unpredictable behavior when Note Toolbar is applied to all folders and viewing expansion of inline folders via MAKE.MD plugin

### ISSUE THREAD

**Issue by joshp12345** [chrisgurney/obsidian-note-toolbar#151] opened 2024-10-08 15:50 UTC
When using MAKE.MD and creating inline links to folders, then using the arrow to expand the folders downward to view inline Flow Blocks, the behavior of Note Toolbars becomes quite erratic if Note Toolbar is configured to appear mapped on all folders. The toolbar may disappear from either the main note or the inline note, may cause the inline note expansion button to not work properly, and for sure the buttons within the inline Flow block do not work if clicked. This is presumably due to the fact that Note Toolbar is not configured to run two instances of itself at the same time on the same tab. 

My suggestion is to find a way to disable any new instances of Note Toolbar in any inline blocks, embeds, etc. when one is already being displayed in the same tab. Or, specifically, disable Note Toolbar within MAKE.MD's flow blocks.

The existing fix is simply to map Note Toolbar to only appear on a select number of folders, or, disable MAKE.MD. However MAKE.MD is a pretty critical plugin, it's not feasible to manually include/exclude Note Toolbar to every specific file or folder unless you severely want to restrict your usage of inline links (via MAKE.MD Flow).

**Comment by chrisgurney** [comment] 2024-10-08 15:56
Thanks for reporting this issue @joshp12345 !

I haven't used MAKE.MD, but my first thought is your suggestion to "disable Note Toolbar within MAKE.MD's flow blocks," is the way to go based on your analysis, but I'll need to dig in more to see what's going on.

I am planning on supporting multiple toolbars in a single note in the future, but it doesn't _sound_ like that would solve this particular problem, due to the way this plugin probably works.

Again, I'll need to dig in with this plugin.

**Comment by chrisgurney** [comment] 2024-10-08 16:39
For my benefit, exact steps to reproduce:

1. In Sandbox vault, install MAKE.MD and Note Toolbar
2. Map a toolbar to all notes (`*`)
3. Use `/` select `Link to Note` and select a folder of notes (e.g., "Adventurer")
4. In the view that appears, next to the search icon, select `Flow View`

The toolbar appears in all flow blocks. Behavior as described by @joshp12345  above.

**Comment by joshp12345** [comment] 2024-10-08 16:47
Thanks for the quick response Chris. I really like using both these plugins and am eagerly awaiting a fix.

By the way, the Toolbar items I use, just so you know my use case are: Open Local Graph, Toggle Properties, Toggle Source View, and Move To Folder.

**Comment by chrisgurney** [comment] 2024-10-08 16:56
@joshp12345 if you change the toolbar's position to `Top (fixed)` that seems to solve this particular problem, by only rendering the toolbar once. That could work as a workaround for now, if you're OK with using the toolbar that way. 

I think what's happening otherwise is that it's injecting the toolbar under the properties/metadata container, which is being rendered/repeated multiple times as you expand the flow view.

As a solution, I think I can try to check for a parent class like `mk-frame` or similar, and if it's present just don't render the toolbar. However, I don't have a mechanism to handle exceptions like this, so since I'm in the core rendering code, I might try to create something a little more general purpose (as an advanced setting, perhaps) to accommodate other plugin issues like this.

**Comment by chrisgurney** [comment] 2024-10-16 15:06
@joshp12345 This should be fixed in `1.14.2`. Please give it a try and let me know how it goes.

**Closed** 2024-10-28 11:23 UTC
Labels: bug, released 🎉
