### ISSUE TITLE
Feature Request - Bottom/Footer toolbar Position

### ISSUE THREAD

**Issue by sqeptyk** [chrisgurney/obsidian-note-toolbar#184] opened 2024-11-07 16:12 UTC
Could you provide an option to make the note toolbar a footer instead of a header?

**Comment by chrisgurney** [comment] 2024-11-07 17:14
@sqeptyk Thanks for the request.

Having the toolbar in the footer is becoming a frequent request, and is on [the roadmap](https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Roadmap). 

It will likely be a floating toolbar, as opposed to be fixed at the bottom like it is at the top. You will be able to adjust its vertical position and styling via the Style Settings plugin.

Thanks again!

**Comment by laktiv** [comment] 2024-11-21 14:27
My vote for this as well.
In addition would great to add style property for panel "small elements" which will decrease the size of elements, because on ios they a bit large for some cases.

**Comment by chrisgurney** [comment] 2024-11-23 01:20
@laktiv There are style settings to adjust icon and font size (see below), but it currently applies to both mobile _and_ desktop. Agreed it might be a good idea to create a mobile version of those settings. Do you think that would address your request?

![CleanShot 2024-11-22 at 20 11 04@2x](https://github.com/user-attachments/assets/e5eff518-f025-4742-841e-2a1b3b78369a)

**Comment by chrisgurney** [comment] 2024-11-25 17:48
@laktiv Gotcha. I think adding support for custom CSS classes per toolbar as suggested in #103 will solve this, then!

**Comment by chrisgurney** [comment] 2024-12-08 15:56
Closing as a duplicate of #37

**Closed by chrisgurney** 2024-12-08 15:56 UTC
Labels: enhancement
