### ISSUE TITLE
Property functions not working

### ISSUE THREAD

**Issue by l-t-k** [chrisgurney/obsidian-note-toolbar#142] opened 2024-09-20 08:53 UTC
**Description of the bug**
The note toolbar plugins adds four new options to the command pallet:
Note Toolbar: Show Properties
Note Toolbar: Hide Properties
Note Toolbar: Folder Properties
Note Toolbar: Toggle Properties

None of them are working if I just execute them using the command pallet

**Steps to reproduce**
Options are not doing anything. Tried with every 'properties in document' option from Editor as well: visible, source, hidden. None of them work

**Plugin, Theme links, and CSS snippets (if applicable):**
Default

**Desktop environment:**
 - OS: Windows 
 - Obsidian version: 1.6.7
 - Note Toolbar version: 1.12.5

**Comment by chrisgurney** [comment] 2024-09-20 10:30
Thanks for the bug report!

- I'm assuming notes have properties on them?
- Are you able to record a video/gif?

**Comment by l-t-k** [comment] 2024-09-20 12:05
1. Yes, they do have properties on them
2. Windows 11 Pro 22631.3880
3. Of course:
![Obsidian_o6bKb3uTHc](https://github.com/user-attachments/assets/48164029-5763-4ddc-a119-c6692cc7eb9b)

I'm using the Blue Topaz theme btw. The grey/blue weird background (that disappears after hovering over it) on the taskbar is something strange as well. I can't find a way to get rid of it after trying every background color config with the style settings pluggin. Any idea?

**Comment by chrisgurney** [comment] 2024-09-20 12:55
Thank you for the details, that helps!

I'll look into the Blue Topaz issue as well; I've noticed similar behavior with a different theme as well.

**Comment by chrisgurney** [comment] 2024-09-20 13:08
This CSS snippet will fix your Blue Topaz issue. If all goes well testing with other themes, I'll add it to the next release.

```
.callout[data-callout="note-toolbar"] {
    background-color: var(--cg-nt-tbar-bg-color) !important;
}
```

**Comment by chrisgurney** [comment] 2024-09-20 13:13
Are you able to open the console and let me know if there's any errors reported while using those commands?

On WIndows, you should be able to open the console with `F12` or `Control` + `Shift` + `I`

**Comment by chrisgurney** [comment] 2024-09-20 13:21
One more thing that might help: Can you run this command `Show debug info` and copy the results to a clipboard, and provide it here?

**Comment by l-t-k** [comment] 2024-09-21 07:26
All other commands work as expected

With the console open, and the debug level on 'all levels': executing one of the toolbar properties commands simple don't generate any debug info at all. Obsidian-git plugin, for example. is generating a lot of messages.

Where to run `Show debug info`? In de console window itself it is not working. On the sources tab I do have the possibility to run command but that command is not part of the list.

Can confirm that you fixed the issue with the Blue Topaz theme in the release by the way, Thanks!

**Comment by chrisgurney** [comment] 2024-09-21 11:23
> With the console open, and the debug level on 'all levels': executing one of the toolbar properties commands simple don't generate any debug info at all. Obsidian-git plugin, for example. is generating a lot of messages.

That's OK. I don't have any output in the production build so you won't see anything, unless there's errors, which is what I was looking for.

> Where to run `Show debug info` ?

1. Use Ctrl+P to open the Command palette
2. Search for `Show debug info`
3. Click the _Copy to clipboard_ button and paste it here

Actually, if you could try running the properties commands this way as well, that could tell me if the button's click handler is working or not, or if it's something more specific in the command.

> Can confirm that you fixed the issue with the Blue Topaz theme in the release by the way, Thanks!

Great to hear!

**Comment by l-t-k** [comment] 2024-09-21 11:34
Oh lol, in Obsidian itself. Here it is:
```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: Blue Topaz v2024071502
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 25
	Plugins enabled: 25
		1: Code Editor Shortcuts v1.14.0
		2: Paste URL into selection v1.7.0
		3: Tasks v7.6.1
		4: Attachment Management v0.9.14
		5: Git v2.24.2
		6: Dataview v0.5.67
		7: Templater v2.4.2
		8: Meta Bind v1.1.3
		9: Excalidraw v2.3.0
		10: Quick Switcher++ v4.4.0
		11: Various Complements v10.0.3
		12: QuickAdd v1.11.1
		13: Custom File Explorer sorting v2.1.13
		14: Iconize v2.14.3
		15: Natural Language Dates v0.6.2
		16: Homepage v4.0.4
		17: Journals v1.4.0
		18: Callout Manager v1.1.0
		19: Charts v3.9.0
		20: Tracker v1.14.0
		21: Heatmap Calendar v0.7.1
		22: Global Search and Replace v0.5.0
		23: Style Settings v1.0.9
		24: Note Toolbar v1.13.1
		25: Remember cursor position v1.0.9

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

Executing the commands through results in the exact same result: nothing happens.

**Comment by chrisgurney** [comment] 2024-09-21 12:03
Thanks for the details! Much appreciated.

Can you reproduce this issue in a sandbox vault?

1. Use Ctrl+P to open the Command palette
2. `Open sandbox vault`
3. Enable plugins, install Note Toolbar, enable it, and add a toolbar with those commands.

**Comment by chrisgurney** [comment] 2024-09-23 21:39
I tried a couple times today to download a Windows 11 VM but couldn't get it to start in VirtualBox. Will try again.

**Comment by l-t-k** [comment] 2024-09-24 06:57
I think I found the issue!

Was trying again with the sandbox vault (tried it already with a complete empty vault) and got the same result when executing one of the notetoolbar properties commands through the command palette. No luck at all. I was pasting my debug info here: 

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Note Toolbar v1.13.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

Only a few options left compared to my normal vault setup so I decided to change some of them to narrow it down. I changed the default editing mode to `Live Preview` and now it is working flawlessly. But I can't imagine you tried already with different editing modes. So probably related to OS (Windows) combined with the source mode I'm editing in?

**Comment by chrisgurney** [comment] 2024-09-24 15:53
@l-t-k Very interesting! Yes, the command definitely doesn't work on Source mode. I might be able to, if there's demand for it.

Either way, hat still doesn't explain your video at the top:

Did you open the tab initially in Source mode, and switch to Live Preview mode, and then try the buttons? Even if I give that a go on my system I can't reproduce the problem.

**Comment by l-t-k** [comment] 2024-09-26 06:39
Yeah, that is absolutely the preferred mode I like to work in! To be honest, I think most people work in that mode.

No, during the video the editor mode has been on source mode.

**Comment by chrisgurney** [comment] 2024-12-21 17:30
@l-t-k I'm closing this issue. Happy to re-open this if you can help narrow down steps to reproduce the issue, with the properties displayed in source mode.

**Closed by chrisgurney** 2024-12-21 17:30 UTC
Labels: bug, cant reproduce
